
melgen:
  _name_: melgen
  in_channels: 80
  out_channels: 80
  diffusion_step_embed_dim_in: 128
  diffusion_step_embed_dim_mid: 512
  diffusion_step_embed_dim_out: 512
  res_channels: 512
  skip_channels: 512
  num_res_layers: 12
  dilation_cycle: 1
  mel_upsample: [2, 2]
  
text:
  #LoRA
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1

attention:
  video_length : 25
  text_length  : 30
  d_model : 512
  
diffusion:
  T: 400
  beta_0: 0.0001
  beta_T: 0.02
  beta: null
dataset:

  # videos_dir: /disk2/yoori0203/VideoToSpeech/LRS3/videos
  # mouthrois_dir: /disk2/yoori0203/VideoToSpeech/LRS3/mouth_rois
  # audios_dir: /disk2/yoori0203/VideoToSpeech/LRS3/audios
  # text_dir : /disk2/yoori0203/VideoToSpeech/LRS3/videos
  videos_dir: /media/4ilab-1/datasets/LRS2/videos
  mouthrois_dir: /media/4ilab-1/datasets/LRS2/mouth_rois
  audios_dir: /media/4ilab-1/datasets/LRS2/audios
  text_dir : /media/4ilab-1/datasets/LRS2/videos
  sampling_rate: ${audio.sampling_rate}
  videos_window_size: 25
  audio_stft_hop: ${audio.hop_length}
  dataset_root: /media/4ilab-1/datasets/LRS2/videos
  # dataset_root: /disk2/yoori0203/VideoToSpeech/LRS3/videos
  
audio:
  sampling_rate: 16000
  filter_length: 640
  hop_length: 160
  win_length: 640
  mel_fmin: 20.0
  mel_fmax: 8000.0

train: # Not used in generate.py
  name: LRS2        # Name of experiment (prefix of experiment name)
  save_dir: null    # where checkpoints will be saved
  ckpt_iter: max    # continue training from a specific iteration
  iters_per_ckpt: 100000
  iters_per_logging: 100
  n_iters: 1000001
  learning_rate: 2e-4
  batch_size_per_gpu: 64

generate:
  name: LRS2
  ckpt_path: exp/LRS2/wnet_h512_d12_T400_betaT0.02/checkpoint/0.pkl           
  n_samples: 3          # Number of utterances from test dataset to be generated 
  video_path: null      # generate audio for a given silent video file
  w_video: 2            # w1 in the paper
  save_dir: save_dir #/disk2/gunwoo/save_generate_mel        # where to save the generated audio
  lipread_text_dir: /media/4ilab-1/datasets/LRS2/LRS2_test_lipreading # directory with predicted text for generating test samples of benchmark dataset 

distributed:
  dist_backend: nccl
  dist_url: tcp://localhost:54321 #54321
